RSDK-6983 Allow users to disable metrics through config
ale7714/viam-telegraf-sensor pull request #8
Opened 2024-03-26 19:35 UTC by ale7714

[RSDK-6983](https://viam.atlassian.net/browse/RSDK-6983)

Decided to go directly to use attributes from config bc it's way easier for the users.

2024-03-26 19:38 UTC, ale7714 commented
Looks like a big PR because I broke down the config into sections but most of the code change is within telegafconfig.go . Getting ready for eventually allowing customer to customize specific metrics.

2024-03-26 19:51 UTC, cheukt requested changes
did a quick pass - some thoughts

- can you update the readme for the new config structure?
- does reconfiguration work?
- would it make sense to disable a few fields by default (e.g. wifi), and tell people how to enable it in the readme?

2024-03-26 22:51 UTC, ale7714 commented
> * can you update the readme for the new config structure?

Done! 

> * does reconfiguration work?

With viam-server running, I update the configuration and see the module reconfigure and additionally validating that the contents of `/tmp/viam-telegraf.conf` has properly updated

```
2024-03-26T18:46:52.011-0400	INFO	robot_server.process.telegraf-sensor_/Users/aleparedes/viam/viam-telegraf-sensor/run.sh.StdOut	pexec/managed_process.go:244	
\_ 2024-03-26T22:46:52.010Z	DEBUG	telegraf-sensor	module/module.go:410	rebuilding	{"name":"rdk:component:sensor/sensorT"}
```

> * would it make sense to disable a few fields by default (e.g. wifi), and tell people how to enable it in the readme?

The two metrics I can think could cause issues are `wireless` and `temp`. Any other that you think is worth disabling by default.

2024-03-27 19:25 UTC, cheukt approved these changes
LGTM

2024-03-27 19:25 UTC, cheukt commented on telegrafsensor/telegrafconfig.go
> +		case "disable_temp", "disable_wireless":
add a comment about why temp/wireless is disabled by default?

2024-03-27 20:24 UTC, merged